before_build:
  - nuget restore
artifacts:
 # pushing a single file with environment variable in path and "Deployment name" specified
  - path: scr\GUI\RequestifyTF2GUI\bin\Debug\RequestifyTF2Forms.exe
    name: myapp
