before_build:
  - nuget restore
artifacts:
 # pushing a single file with environment variable in path and "Deployment name" specified
  - path: scr\GUI\RequestifyTF2GUI\bin\Debug\RequestifyTF2GUI.exe
    name: forms
  - path: scr\Plugins\MTTSPlugin\bin\Debug\MTTSPlugin.dll
    name: mtts
  - path: scr\Plugins\RequestPlugin\bin\Debug\RequestPlugin.dll
    name: reqmusic
  - path: scr\Plugins\TTSPlugin\bin\Debug\TTSPlugin.dll
    name: tts
  - path: scr\Core\RequestifyTF2\bin\Debug\RequestifyTF2.dll
    name: core
  - path: scr\Plugins\GrandTTS\bin\Debug\GrandTTS.dll
    name: gtts
  - path: scr\Plugins\RawPlugin\bin\Debug\RawPlugin.dll
    name: raw
  - path: scr\Plugins\RussianTTS\bin\Debug\RussianTTS.dll
    name: rtts
